### ISSUE TITLE
Idea: Merge data with MDN page

### ISSUE THREAD

**Issue by JakeChampion** [nolanlawson/html5workertest#13]
I just came across a similar MDN page (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers), it might be useful to merge these two resources together.

**Comment by nolanlawson** [comment]
I'm open to offering the data in an easy-to-consume format so that it can be used to automatically populate MDN. In fact the data is already available; it's just a little hard to grok because it's the raw results: https://nolan.cloudant.com/html5workertest (Cloudant database; use `_all_docs?include_docs=true` to download all the results or use `pouchdb-dump-cli` etc.).
