### ISSUE TITLE
Why do we document `navigator.product`?

### ISSUE THREAD

**Issue by JakeChampion** [nolanlawson/html5workertest#2]
`navigation.product` must [always return the string Gecko](https://html.spec.whatwg.org/multipage/webappapis.html#dom-navigator-product). I'm not sure why this is a useful feature to have in a Worker which makes me wonder why it is included in this list. Is there a reason it needs to exist in a Worker context?

**Comment by nolanlawson** [comment]
I mostly added it for completeness and out of curiosity... it can definitely be removed, yeah. :+1:

**Comment by nolanlawson** [comment]
Per discussion in #8 I think we should just add a little ℹ️ or something that links to the relevant blog post/issue/etc. This is designed to be an informational resource, but we can remove red X's for stuff that doesn't make any sense to look "danger-y."

**Comment by domenic** [comment]
But the question is, "why navigator.product or DOMCursor and not (some other completely random API)?" E.g. why does the table not contain HTMLCanvasElement or InstallTrigger or navigator.oscpu?

**Comment by nolanlawson** [comment]
I basically just grabbed APIs from Edge's WebIDL plus MDN's [functions and classes available to workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers). It's a weird grab-bag, to be sure.

HTMLCanvasElement may make sense given that Moz is working on adding Canvas 2d and WebGL support, but I've punted on it for now because they're still behind flags and only available in Firefox nightly.

I guess the best way to state my goal is: developers can open this page, Ctrl-F, and find whatever API they're interested in. It's not supposed to be used as a scoring metric, hence why I didn't add a big grand total ala HTML5Test or HTML5Accessibility. Perhaps it should be renamed.

**Comment by domenic** [comment]
> I guess the best way to state my goal is: developers can open this page, Ctrl-F, and find whatever API they're interested in.

Right. I think that's a good goal. But I think your data sources do not serve that goal at all. Developers do not care about navigator.product or DOMCursor.

**Comment by nolanlawson** [comment]
Happy to take PRs to add new APIs or soften the presentation of esoteric ones. :) E.g. estoteric ones can be grouped under "Miscellaneous" or even "Deprecated."

**Comment by domenic** [comment]
I still don't get why you think it's important to have navigator.product and not have, say, navigator.oscpu. Your only argument so far seems to be that some MDN page has the former and not the latter. Should I edit the MDN page to remove it? I'd prefer a more objective criterion.

**Comment by nolanlawson** [comment]
I'd prefer to have more information rather than less. Agreed that `navigator.product` is a bit silly, happy to add `navigator.oscpu` and remove `product`.
